# Generated by Django 4.0 on 2023-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=100)),
                ('thumb_url', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_activity', models.TextField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('unchangeable', models.BooleanField(default=False)),
                ('include_weekly_report', models.BooleanField(default=False)),
                ('content_type', models.IntegerField()),
                ('is_netology', models.BooleanField(default=False)),
                ('bg_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('custom_author_names', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_contents_link', models.URLField(blank=True, null=True)),
                ('hide_viewer_navigation', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('competences', models.JSONField()),
            ],
        ),
    ]
